version: "3.8"
services:
  mongodb-dev:
    image: mongo
    container_name: mongodb
    ports:
      - 27017:27017
    volumes:
      - data:/data
    environment:
      - MONGO_INITDB_ROOT_USERNAME=rootuser
      - MONGO_INITDB_ROOT_PASSWORD=rootpass
  spring-app-dev:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: spring-app
    restart: always
    ports:
      - 10000:10000
    depends_on:
      - mongodb-dev
  openai-service-dev:
    build:
      context: ./services/openai-service
      dockerfile: Dockerfile
    container_name: openai-service
    restart: always
    ports:
      - 10001:10001
    depends_on:
      - mongodb-dev
volumes:
  data: {}

networks:
  default:
    name: mongodb_network
